html5up-dopetrope-mvc/Models/TB_News.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace html5up_dopetrope_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_News
    {
        public int ID { get; set; }
        public System.DateTime PostDateTime { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool IsDelete { get; set; }
    }
}

html5up-dopetrope-mvc/Areas/Admin/Controllers/TB_NewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using html5up_dopetrope_mvc.Models;

namespace html5up_dopetrope_mvc.Areas.Admin.Controllers
{
    using PagedList;

    public class TB_NewsController : Controller
    {
        private BedAndBreakfastEntities db = new BedAndBreakfastEntities();

        private int pageSize = 10;

        // GET: Admin/TB_News
        public ActionResult Index(int page = 1)
        {
            int currentPage = page < 1 ? 1 : page;

            return View(db.TB_News.OrderByDescending(desc => desc.PostDateTime).ToPagedList(currentPage, pageSize));
        }

        // GET: Admin/TB_News/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TB_News tB_News = db.TB_News.Find(id);
            if (tB_News == null)
            {
                return HttpNotFound();
            }
            return View(tB_News);
        }

        // GET: Admin/TB_News/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/TB_News/Create
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,PostDateTime,Title,Description,IsDelete")] TB_News tB_News)
        {
            if (ModelState.IsValid)
            {
                db.TB_News.Add(tB_News);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tB_News);
        }

        // GET: Admin/TB_News/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TB_News tB_News = db.TB_News.Find(id);
            if (tB_News == null)
            {
                return HttpNotFound();
            }
            return View(tB_News);
        }

        // POST: Admin/TB_News/Edit/5
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,PostDateTime,Title,Description,IsDelete")] TB_News tB_News)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tB_News).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tB_News);
        }

        // GET: Admin/TB_News/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TB_News tB_News = db.TB_News.Find(id);
            if (tB_News == null)
            {
                return HttpNotFound();
            }
            return View(tB_News);
        }

        // POST: Admin/TB_News/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TB_News tB_News = db.TB_News.Find(id);
            db.TB_News.Remove(tB_News);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

html5up-dopetrope-mvc/Areas/Admin/Views/TB_News/Create.cshtml
@model html5up_dopetrope_mvc.Models.TB_News

@{
    ViewBag.Title = "最新消息-新增";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="main-wrapper">
    <div class="container">
        <div class=" ">
            @using (Html.BeginForm("Create", "TB_News", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                <div class="panel panel-default">
                    @Html.AntiForgeryToken()
                    <div>
            
                        <div class="panel-heading">
                            <h3 class="panel-title">@ViewBag.Title</h3>
                        </div>

                        <div class="panel-body">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group ">
                                @Html.LabelFor(model => model.PostDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.PostDateTime, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.PostDateTime, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            @*<div class="form-group">
            @Html.LabelFor(model => model.IsDelete, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsDelete)
                    @Html.ValidationMessageFor(model => model.IsDelete, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>*@

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    @*<form action="@Url.Action("Index", "TB_News", new { @class = "", area = "Admin" })" method="GET">
                    <button type="submit" class="btn btn-default">Cancel</button>
                </form>*@
                                    @*@Html.ActionLink("Back to List", "Index", new { @class = "btn btn-default" })*@
                                    <input type="submit" value="送出" class="btn btn-default" />
                                    <div class="btn btn-default">
                                        @Html.ActionLink("回上一頁", "Index")
                                    </div>
                                </div>

                            </div>
                        </div>
                     
                    </div>
                </div>
               
            }
            @*<div>
                    @Html.ActionLink("Back to List", "Index")
                </div>*@
        </div>
    </div>

</div>

@section Style
{
    <link href="~/Content/bootstrap.spacelab.min.css" rel="stylesheet" />
}

@section Scripts
{
    <script>
    </script>
}

html5up-dopetrope-mvc/Areas/Admin/Views/TB_News/Delete.cshtml
@model html5up_dopetrope_mvc.Models.TB_News

@{
    ViewBag.Title = "最新消息-刪除";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="main-wrapper">
    <div class="container">
        <div class=" ">
   
        
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">@ViewBag.Title</h3>
                </div>
           
                <dl class="panel-body">
                    <dt>
                        @Html.DisplayNameFor(model => model.PostDateTime)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.PostDateTime)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Title)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Title)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Description)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Description)
                    </dd>

                    @*<dt>
                        @Html.DisplayNameFor(model => model.IsDelete)
                    </dt>*@

                    @*<dd>
                        @Html.DisplayFor(model => model.IsDelete)
                    </dd>*@

                </dl>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <h3>您確定要刪除嗎？</h3>
                        <input type="submit" value="送出" class="btn btn-default" />
                        <div class="btn btn-default">
                            @Html.ActionLink("回上一頁", "Index")
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
@section Style
{
    <link href="~/Content/bootstrap.spacelab.min.css" rel="stylesheet" />
}

@section Scripts
{
    <script>
    </script>
}

html5up-dopetrope-mvc/Areas/Admin/Views/TB_News/Details.cshtml
@model html5up_dopetrope_mvc.Models.TB_News

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>TB_News</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PostDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostDateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDelete)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDelete)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

html5up-dopetrope-mvc/Areas/Admin/Views/TB_News/Edit.cshtml
@model html5up_dopetrope_mvc.Models.TB_News

@{
    ViewBag.Title = "最新消息-編輯";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="main-wrapper">
    <div class="container">
        @using (Html.BeginForm("Edit", "TB_News", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">@ViewBag.Title</h3>
                </div>
                <div class="panel-body">
            
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ID)

                    <div class="form-group">
                        @Html.LabelFor(model => model.PostDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.PostDateTime, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.PostDateTime, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    @*<div class="form-group">
                        @Html.LabelFor(model => model.IsDelete, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="checkbox">
                                @Html.EditorFor(model => model.IsDelete)
                                @Html.ValidationMessageFor(model => model.IsDelete, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>*@

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="送出" class="btn btn-default" />
                            <div class="btn btn-default">
                                @Html.ActionLink("回上一頁", "Index")
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }

   
    </div>

</div>

@section Style
{
    <link href="~/Content/bootstrap.spacelab.min.css" rel="stylesheet" />
}

@section Scripts
{
    <script>
    </script>
}

html5up-dopetrope-mvc/Areas/Admin/Views/TB_News/Index.cshtml
 
@using PagedList.Mvc
@model PagedList.IPagedList<html5up_dopetrope_mvc.Models.TB_News>

@{
    ViewBag.Title = "最新消息資料維護";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="main-wrapper">
    <div class="container">
   
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">@ViewBag.Title</h3>
            </div>

            <div class="panel-body">

                <table class="table table-striped table-hover ">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.FirstOrDefault().PostDateTime)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.FirstOrDefault().Title)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.FirstOrDefault().Description)
                            </th>
                     
                            <th>功能</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.PostDateTime)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Title)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Description)
                                </td>
                      
                                <td>
                                    @Html.ActionLink("編輯", "Edit", new { id = item.ID }) |
                         
                                    @Html.ActionLink("刪除", "Delete", new { id = item.ID })
                                </td>
                            </tr>
                        }
                    </tbody>
                    <tfoot>
                        <form action="@Url.Action("Create", "TB_News", new { @class = "", area = "Admin" })" method="GET">
                            <button type="submit" class="btn btn-default">新增</button>
                        </form>
                    </tfoot>
                </table>
            </div>
            <div class="panel-footer">
                @Html.PagedListPager(Model, page => Url.Action("Index", "TB_News", new { page = page, area = "Admin" }))
            </div>
        </div>


    </div>
</div>
@section Style
{
    <link href="~/Content/bootstrap.spacelab.min.css" rel="stylesheet" />
}
@section Scripts
{
    <script>
    </script>
}